# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: flink
      image: ghcr.io/devthefuture-org/containers/flink:2.1.0-debian-12-r1
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 2.1.0
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Flink is a framework and distributed processing engine for stateful
  computations over unbounded and bounded data streams.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/flink/img/flink-stack-220x234.png
keywords:
- flink
- stream-processing
- batch-processing
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: flink
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/flink
version: 2.0.8
