# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: grafana
      image: ghcr.io/devthefuture-org/containers/grafana:12.1.1-debian-12-r1
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 12.1.1
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Grafana is an open source metric analytics and visualization suite for
  visualizing time series data that supports various types of data sources.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/grafana/img/grafana-stack-220x234.png
keywords:
- analytics
- monitoring
- metrics
- logs
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: grafana
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/grafana
version: 12.1.9
