# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: fluxcd-helm-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-helm-controller:1.3.0-debian-12-r9
    - name: fluxcd-image-automation-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-image-automation-controller:0.41.2-debian-12-r4
    - name: fluxcd-image-reflector-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-image-reflector-controller:0.35.2-debian-12-r4
    - name: fluxcd-kustomize-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-kustomize-controller:1.6.1-debian-12-r5
    - name: fluxcd-notification-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-notification-controller:1.6.0-debian-12-r8
    - name: fluxcd-source-controller
      image: ghcr.io/devthefuture-org/containers/fluxcd-source-controller:1.6.2-debian-12-r6
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.6.2
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Source Controller is a component of Flux. Flux is a tool for keeping
  Kubernetes clusters in sync with sources of configuration.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
- deployment
- gitops
- cd
- continuous-delivery
- helm
- kustomize
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: flux
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/flux
version: 2.4.37
