# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kube-state-metrics
      image: ghcr.io/devthefuture-org/containers/kube-state-metrics:2.16.0-debian-12-r5
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 2.16.0
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: kube-state-metrics is a simple service that listens to the Kubernetes
  API server and generates metrics about the state of the objects.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/kube-state-metrics/img/kube-state-metrics-stack-220x234.png
keywords:
- prometheus
- kube-state-metrics
- monitoring
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: kube-state-metrics
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/kube-state-metrics
version: 5.1.1
