# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: git
      image: ghcr.io/devthefuture-org/containers/git:2.51.0-debian-12-r0
    - name: mlflow
      image: ghcr.io/devthefuture-org/containers/mlflow:3.3.2-debian-12-r0
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 3.3.2
dependencies:
- condition: minio.enabled
  name: minio
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 17.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 16.x.x
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: MLflow is an open-source platform designed to manage the end-to-end machine
  learning lifecycle. It allows you to track experiments, package code into reproducible
  runs, and share and deploy models.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mlflow/img/mlflow-stack-220x234.png
keywords:
- mlflow
- models
- python
- machine
- learning
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: mlflow
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/mlflow
- https://github.com/bitnami/containers/tree/main/bitnami/mlflow
- https://github.com/mlflow/mlflow
version: 5.1.18
