# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: keycloak
      image: ghcr.io/devthefuture-org/containers/keycloak:26.3.3-debian-12-r0
    - name: keycloak-config-cli
      image: ghcr.io/devthefuture-org/containers/keycloak-config-cli:6.4.0-debian-12-r11
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 26.3.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 16.x.x
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Keycloak is a high performance Java-based identity and access management
  solution. It lets developers add an authentication layer to their applications with
  minimum effort.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/keycloak/img/keycloak-stack-220x234.png
keywords:
- keycloak
- access-management
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: keycloak
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/keycloak
version: 25.2.1
