# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: cassandra
      image: ghcr.io/devthefuture-org/containers/cassandra:5.0.5-debian-12-r7
    - name: cassandra-exporter
      image: ghcr.io/devthefuture-org/containers/cassandra-exporter:2.3.8-debian-12-r51
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 5.0.5
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Apache Cassandra is an open source distributed database management system
  designed to handle large amounts of data across many servers, providing high availability
  with no single point of failure.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/cassandra/img/cassandra-stack-220x234.png
keywords:
- cassandra
- database
- nosql
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: cassandra
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/cassandra
version: 12.3.12
