# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: acmesolver
      image: ghcr.io/devthefuture-org/containers/acmesolver:1.18.2-debian-12-r5
    - name: cainjector
      image: ghcr.io/devthefuture-org/containers/cainjector:1.18.2-debian-12-r5
    - name: cert-manager
      image: ghcr.io/devthefuture-org/containers/cert-manager:1.18.2-debian-12-r5
    - name: cert-manager-webhook
      image: ghcr.io/devthefuture-org/containers/cert-manager-webhook:1.18.2-debian-12-r5
  licenses: Apache-2.0
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 1.18.2
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: cert-manager is a Kubernetes add-on to automate the management and issuance
  of TLS certificates from various issuing sources.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/cert-manager/img/cert-manager-stack-220x234.png
keywords:
- go
- security
- tls
- certificate
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: cert-manager
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/cert-manager
version: 1.5.15
