# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: kubectl
      image: ghcr.io/devthefuture-org/containers/kubectl:1.33.4-debian-12-r0
    - name: mongodb
      image: ghcr.io/devthefuture-org/containers/mongodb:8.0.13-debian-12-r0
    - name: mongodb-exporter
      image: ghcr.io/devthefuture-org/containers/mongodb-exporter:0.47.0-debian-12-r1
    - name: nginx
      image: ghcr.io/devthefuture-org/containers/nginx:1.29.1-debian-12-r0
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r51
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.0.13
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it
  stores data in JSON-like documents. Automated scalability and high-performance.
  Ideal for developing cloud native applications.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: mongodb
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/mongodb
version: 17.0.0
