# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: mastodon
      image: ghcr.io/devthefuture-org/containers/mastodon:4.4.3-debian-12-r8
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 4.4.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 22.x.x
- condition: postgresql.enabled
  name: postgresql
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 16.x.x
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 22.x.x
- condition: minio.enabled
  name: minio
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 17.x.x
- condition: apache.enabled
  name: apache
  repository: oci://ghcr.io/devthefuture-org/charts
  version: 11.x.x
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: Mastodon is self-hosted social network server based on ActivityPub. Written
  in Ruby, features real-time updates, multimedia attachments and no vendor lock-in.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mastodon/img/mastodon-stack-220x234.png
keywords:
- development
- dashboards
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: mastodon
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/mastodon
version: 14.0.1
