# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: consul
      image: ghcr.io/devthefuture-org/containers/consul:1.21.4-debian-12-r1
    - name: consul-exporter
      image: ghcr.io/devthefuture-org/containers/consul-exporter:0.13.0-debian-12-r29
    - name: os-shell
      image: ghcr.io/devthefuture-org/containers/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: application
apiVersion: v2
appVersion: 1.21.4
dependencies:
- name: common
  repository: oci://ghcr.io/devthefuture-org/charts
  tags:
  - bitnami-common
  version: 2.x.x
description: HashiCorp Consul is a tool for discovering and configuring services in
  your infrastructure.
home: https://github.com/devthefuture-org
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/consul/img/consul-stack-220x234.png
keywords:
- discovering
- configuring
- services
maintainers:
- name: DevTheFuture
  url: https://github.com/devthefuture-org/charts
name: consul
sources:
- https://github.com/devthefuture-org/charts/tree/main/openami/consul
version: 11.4.33
